#!/bin/bash

HOST_HTTP_PORT=3080
HOST_SSH_PORT=3022

if [[ $# -lt 1 ]]; then
  sudo docker run -ti -p $HOST_HTTP_PORT:80 -p $HOST_SSH_PORT:22 ocontant/centos6-icinga2
else
  sudo docker run -ti -p $HOST_HTTP_PORT:80 -p $HOST_SSH_PORT:22 -v ./content/etc/icinga2:/etc/icinga2 -v ./content/etc/icingaweb2:/etc/icingaweb2 ocontant/centos6-icinga2
fi
